name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Change to your preferred Node version

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # If your build output is not in 'dist', change 'dist' to your build output directory
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      # Optionally, clean-up cached GH Pages
      - name: Clean up old deployments
        run: echo "Cleanup not needed with peaceiris/actions-gh-pages"